- name: Alacritty
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Install Alacritty (Linux)
      become: yes
      command: snap install alacritty --classic
      args:
        creates: /snap/bin/alacritty
      when: not is_mac and not is_wsl

    # macOS

    - name: Install Alacritty (macOS)
      homebrew_cask:
        name: alacritty
      when: is_mac
