- name: git
  hosts: 127.0.0.1
  connection: local

  vars:
    distribution_fallback:
      'Pop!_OS': 'Ubuntu'
    distribution: "{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) }}"
    is_ubuntu_bionic: "{{ ansible_distribution_release == 'bionic' }}"
    linux_git_packages:
      - git
      - git-gui
      - git-lfs
      - gitk

  tasks:
    - name: Add Git APT package key
      become: yes
      get_url:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xa1715d88e1df1f24
        dest: /etc/apt/keyrings/git.asc
        mode: 0644

    - name: Add Git APT package repository
      become: yes
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/git.asc] http://ppa.launchpad.net/git-core/ppa/{{ distribution | lower }} {{ ansible_distribution_release }} main
        filename: git
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install APT package
      become: yes
      apt:
        package: "{{ item }}"
      loop: "{{ linux_git_packages }}"

    - name: "[Ubuntu 18.04] Determine latest version"
      shell:
        cmd: "curl -s https://api.github.com/repos/BurntSushi/ripgrep/releases/latest | grep \"browser_download_url.*deb\" | grep amd64 | cut -d : -f 2,3 | tr -d \\\""
        warn: false
      register: ripgrep_version
      when: is_ubuntu_bionic

    - name: "[Ubuntu 18.04] Install ripgrep"
      become: yes
      apt:
        deb: "{{ ripgrep_version.stdout }}"
      when: is_ubuntu_bionic

    - name: "[Other Linux] Install ripgrep"
      become: yes
      apt:
        package: ripgrep
      when: not is_ubuntu_bionic
