- name: git
  hosts: 127.0.0.1
  connection: local

  vars:
    is_debian: "{{ ansible_distribution == 'Debian' }}"
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS' }}"
    is_ubuntu_bionic: "{{ ansible_distribution_release == 'bionic' }}"
    linux_git_packages:
      - git
      - git-gui
      - git-lfs
      - gitk

  tasks:
    - name: "[Ubuntu] Add Git APT package repository"
      become: yes
      apt_repository:
        repo: ppa:git-core/ppa
        filename: git
        update_cache: no
      register: apt_repository_1
      when: is_ubuntu

    - name: "[Debian] Add Backports repository"
      become: yes
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
        filename: backports
        update_cache: no
      register: apt_repository_2
      when: is_debian

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository_1.changed or apt_repository_2.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: "[Debian] Install APT package"
      become: yes
      apt:
        package: "{{ item }}"
        default_release: "{{ ansible_distribution_release }}-backports"
      loop: "{{ linux_git_packages }}"
      when: is_debian

    - name: "[Non-Debian] Install APT package"
      become: yes
      apt:
        package: "{{ item }}"
      loop: "{{ linux_git_packages }}"
      when: not is_debian

    - name: "[Ubuntu 18.04] Determine latest version"
      shell:
        cmd: "curl -s https://api.github.com/repos/BurntSushi/ripgrep/releases/latest | grep \"browser_download_url.*deb\" | grep amd64 | cut -d : -f 2,3 | tr -d \\\""
        warn: false
      register: ripgrep_version
      when: is_ubuntu_bionic

    - name: "[Ubuntu 18.04] Install ripgrep"
      become: yes
      apt:
        deb: "{{ ripgrep_version.stdout }}"
      when: is_ubuntu_bionic

    - name: "[Other Linux] Install ripgrep"
      become: yes
      apt:
        package: ripgrep
      when: not is_ubuntu_bionic
