#########################################################################################
#
#  Note that import order here is important, so rearranging import lists
#  is *not* recommended.
#
#########################################################################################

- name: Configure machine for development work
  hosts: 127.0.0.1
  connection: local

##### Operating system packages and configuration

- import_playbook: core.yaml

##### Developer tools

# Visual Studio Code
- import_playbook: vscode/core.yaml

# Docker
- import_playbook: docker/core.yaml

# git
- import_playbook: git/core.yaml


# Virtualization (QEMU/KVM)
- import_playbook: virtualization/core.yaml


# NodeJS
- import_playbook: nodejs/core.yaml

# Postman
- import_playbook: postman/core.yaml

# PowerShell Core
- import_playbook: powershell-core/core.yaml

# Python
- import_playbook: python/core.yaml

##### Applications (free)


# Microsoft Edge
- import_playbook: edge/core.yaml

# Prettier version of ping w/ graphs
- import_playbook: prettyping/core.yaml

# Slack desktop application
- import_playbook: slack/core.yaml

# VideoLan Client (primarily for codecs)
- import_playbook: vlc/core.yaml

##### Applications (commercial license required)

# Google Backup and Sync (compatible; using Insync on Linux)
- import_playbook: google-backup/core.yaml
