- name: Docker
  hosts: 127.0.0.1
  connection: local

  vars:
    distribution_fallback:
      'Pop!_OS': 'Ubuntu'
    distribution_release_fallback:
      'impish': 'hirsute'
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS' }}"
    nvidia_distribution_version_fallback:
      '21.10': '20.04'

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Determine Docker Compose latest version
      shell:
        cmd: "curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -i \"browser_download_url.*linux-x86_64\\\"\" | cut -d : -f 2,3 | tr -d \\\""
        warn: false
      register: docker_compose_version

    - name: Install Docker Compose
      become: yes
      get_url:
        url: "{{ docker_compose_version.stdout }}"
        dest: /usr/local/bin/docker-compose
        mode: 0755

    - name: Add Docker APT package key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) | lower }}/gpg

    - name: Add Docker APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) | lower }} {{ distribution_release_fallback[ansible_distribution_release] | default(ansible_distribution_release) }} stable
        filename: docker
        update_cache: no
      register: apt_repository_docker

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository_docker.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Docker engine
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - docker-ce
        - docker-ce-cli

    - name: Enable Docker engine for current user
      become: yes
      user:
        name={{ lookup('env', "USER") }}
        groups=docker
        append=yes

    - name: "[Ubuntu] Add Mesa package source"
      become: yes
      apt_repository:
        repo: ppa:kisak/kisak-mesa
      register: apt_repository_mesa
      when: is_ubuntu

    - name: "[Ubuntu] Update APT package list"
      become: yes
      apt:
        update_cache: yes
      when: is_ubuntu and apt_repository_mesa.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: "[Ubuntu] Install Mesa libraries and utilities"
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - libglapi-mesa
        - libglx-mesa0
        - mesa-utils
      when: is_ubuntu

    - name: "[Ubuntu] Add NVIDIA container runtime APT package key"
      become: yes
      apt_key:
        url: https://nvidia.github.io/nvidia-container-runtime/gpgkey
      when: is_ubuntu

    - name: "[Ubuntu] Add NVIDIA container runtime APT package source"
      become: yes
      get_url:
        dest: /etc/apt/sources.list.d/nvidia-container-runtime.list
        url: https://nvidia.github.io/nvidia-container-runtime/ubuntu{{ nvidia_distribution_version_fallback[ansible_distribution_version] | default(ansible_distribution_version) }}/nvidia-container-runtime.list
      register: apt_repository_nvidia
      when: is_ubuntu

    - name: "[Ubuntu] Update APT package list"
      become: yes
      apt:
        update_cache: yes
      when: is_ubuntu and apt_repository_nvidia.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: "[Ubuntu] Install NVIDIA container runtime"
      become: yes
      apt:
        package: nvidia-container-runtime
      when: is_ubuntu

    - name: Determine Docker Machine latest version
      shell:
        cmd: "curl -s https://api.github.com/repos/docker/machine/releases/latest | grep \"browser_download_url.*Linux-x86_64\\\"\" | cut -d : -f 2,3 | tr -d \\\""
        warn: false
      register: docker_machine_version

    - name: Install Docker Machine
      become: yes
      get_url:
        url: "{{ docker_machine_version.stdout }}"
        dest: /usr/local/bin/docker-machine
        mode: 0755
