- name: Virtualization
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: "[Non-WSL] Test for hypervisor"
      shell: dmesg | grep -i "hypervisor detected" || true
      register: hypervisor
      when: not is_wsl

    - name: "[Non-WSL] Install QEMU/KVM"
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - bridge-utils
        - libvirt-clients
        - libvirt-daemon-system
        - ovmf
        - qemu-kvm
        - virt-manager
      when: not is_wsl and hypervisor.stdout == ""

    - name: "[Non-WSL] Enable QEMU/KVM for current user"
      become: yes
      user:
        name={{ lookup('env', "USER") }}
        groups=libvirt
        append=yes
      when: not is_wsl and hypervisor.stdout == ""
