- name: .NET
  hosts: 127.0.0.1
  connection: local

  vars:
    distribution_fallback:
      'Pop!_OS': 'Ubuntu'
    distribution_release_fallback:
      'impish': 'hirsute'
    distribution_version_fallback:
      '21.10': '21.04'
    dotnet_runtime_versions:
      - "3.1"
    dotnet_sdk_version: "6.0"

  tasks:
    - name: Add Microsoft APT package key
      become: yes
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add Microsoft APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/{{ distribution_fallback[ansible_distribution] | default(ansible_distribution) | lower }}/{{ ansible_distribution_major_version if ansible_distribution == 'Debian' else distribution_version_fallback[ansible_distribution_version] | default(ansible_distribution_version) }}/prod {{ distribution_release_fallback[ansible_distribution_release] | default(ansible_distribution_release) }} main
        filename: microsoft-prod
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install .NET SDK {{ dotnet_sdk_version }}
      become: yes
      apt:
        package: dotnet-sdk-{{ dotnet_sdk_version }}
      register: dotnet_sdk_installed_linux

    - name: Install ASP.NET Runtime
      become: yes
      apt:
        package: aspnetcore-runtime-{{ item }}
      loop: "{{ dotnet_runtime_versions }}"

    - name: Perform first-run experience
      command: dotnet new
      when: dotnet_sdk_installed_linux.changed

    - name: Update environment for .NET Core
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: .NET Core enhancement"
        block: |
          export PATH=$PATH:$HOME/.dotnet/tools
