- name: Microsoft Edge
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Add Microsoft APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/edge/ stable main
        filename: microsoft-edge
        update_cache: no
      register: apt_repository
      when: not is_mac and not is_wsl

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Microsoft Edge (Linux)
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - fonts-liberation
        - microsoft-edge-stable
      when: not is_mac and not is_wsl

    # macOS (TODO)
