- import_playbook: ../golang/core.yaml

- name: Hivemind
  hosts: 127.0.0.1
  connection: local

  vars:

  tasks:
    - name: Install Hivemind
      shell:
        cmd: GO111MODULE=on /usr/local/go/bin/go get -u -f github.com/DarthSim/hivemind
        creates: $HOME/go/bin/hivemind
