- name: Remmina
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: "[Non-WSL] Add Remmina APT package repository"
      become: yes
      apt_repository:
        repo: ppa:remmina-ppa-team/remmina-next
        filename: remmina
        update_cache: no
      register: apt_repository
      when: not is_wsl

    - name: "[Non-WSL] Update APT package list"
      become: yes
      apt:
        update_cache: yes
      when: not is_wsl and apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: "[Non-WSL] Install Remmina"
      become: yes
      apt:
        package: remmina
      when: not is_wsl
