- name: Remmina
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Add Remmina APT package repository (Ubuntu)
      become: yes
      apt_repository:
        repo: ppa:remmina-ppa-team/remmina-next
        filename: remmina
        update_cache: no
      register: apt_repository
      when: is_ubuntu and not is_wsl

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: is_ubuntu and not is_wsl and apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Remmina
      become: yes
      apt:
        package: remmina
      when: not is_mac and not is_wsl
